Update hologamev.py
AILab-FOI/PRRI-HoloGameV2024 pull request #47
Opened 2024-04-24 06:21 UTC by ndupanovi20

Prvobitni dizajn 2. levela, treba raspraviti o mjestima enemy-a  i dali su lava (damage) i voda (plivati/hodati kroz nju) mogućnost za biti na mapi.
![Lava](https://github.com/AILab-FOI/PRRI-HoloGameV2024/assets/93327722/28d1c889-c5a7-4ec2-bbeb-d8d3185231b1)
![Voda](https://github.com/AILab-FOI/PRRI-HoloGameV2024/assets/93327722/1fdd9421-246c-4b6a-b75c-6a25bad5b91a)

2024-04-24 08:31 UTC, ndupanovi20 commented
Vrata sam stavljao po mapi tkd ću kasnije ispraviti da ih uklonima samo da na kraju imaju

2024-04-24 08:46 UTC, mmarkoovin21 submitted a review, later dismissed

2024-04-24 08:54 UTC, mmarkoovin21 commented
Jako mi se sviđa što si napravio!
Par napomena samo:
- mislim da će vodu biti malo teže implementirati pa bi je za sada izbacila 
-lava je super ideja, ako hoćeš, umjesto vode možeš staviti kao neku kiselinu zalenu ili nesto slicno
- povecala bi jos samo malo razmak na onoj velikoj lavi da bude izazovnije isto tako imaš jedan ndio gdje su cijevi i dosta ostalih letećih stvari na koje zapravo igrač ne može baš lagano skočiti pa neznam jesi li ih mislio koristiti ili je to samo neka pozadina
- Moramo vidjeti kako ćemo implementirati  ljestve

2024-04-24 09:03 UTC, mmarkoovin21 requested changes
Par napomena samo:
- mislim da će vodu biti malo teže implementirati pa bi je za sada izbacila (još ćemo o tome raspravljati na vježbama danas)
- lava je super ideja, ako hoćeš, umjesto vode možeš staviti kao neku kiselinu zalenu ili nesto slicno
- povecala bi jos samo malo razmak na onoj velikoj lavi da bude izazovnije isto tako imaš jedan ndio gdje su cijevi i dosta ostalih letećih stvari na koje zapravo igrač ne može baš lagano skočiti pa neznam jesi li ih mislio koristiti ili je to samo neka pozadina
- Moramo vidjeti kako ćemo implementirati  ljestve


Neću ti još onda mergeat pull request dok ne doradiš te neke stvari stvari, ok?

2024-05-08 04:43 UTC, ndupanovi20 commented
Imam problem dodavanja neprijatelja, kad pokušam ih postaviti ostaju mi tajlovi umjesto neprijatelja na mapi ili obrnuto zavisnosti jel gledam tajlove ili character editor
![Screenshot 2024-05-08 064110](https://github.com/AILab-FOI/PRRI-HoloGameV2024/assets/93327722/b1ce8e43-cfb0-47f3-a3bb-8798ec56d48f)
, te mislim da je samo još to ostalo da se uradi na mapi.

2024-05-09 16:30 UTC, merged